### PR TITLE
Refactor data file

### PR DESCRIPTION
**Pull request by oesukam**
#### What does this PR do?
This PR puts provinces, districts and sectors into different files in order to improve the code maintainability

#### How to test?
- Clone the repo
- Use the snippet below
```js
const { Provinces, Districts } = require('rwanda');

console.log(Provinces()); // [ 'East', 'Kigali', 'North', 'South', 'West' ]
console.log(Districts()); // [ 'Bugesera', 'Gatsibo', 'Kayonza', 'Kirehe',...]
```

### CODE REVIEW

**Review by knowbee — COMMENTED** [review]
This looks so great, but please check contributing guideline on the section of [(making changes](https://github.com/knowbee/rwanda/blob/master/CONTRIBUTING.md#making-a-change)).

Make sure your changes are pushed on the feature branch (eg: feature-refactor-data, etc..) off the develop branch not directly to the master branch.

**Comment by oesukam** [comment]
@knowbee Thanks for the feedback. I just updated it to `develop`.

**Comment by knowbee** [comment]
> @knowbee Thanks for the feedback. I just updated it to `develop`.

You can also rename you branch to ft-refactor-data-file or feature-refactor-data-file so that future pull requests follow the same format. Thanks

**Comment by oesukam** [comment]
@knowbee I think `ft` or `feature` would more make sens if it was about adding a new feature but this PR doesn't change the current implementation but only refactor the codebase. We can maybe have `feature` (New feature), `refactor` (Refactor the codebase), `bug` (fixing bug), `chore` (improving the development environment)

**Comment by knowbee** [comment]
> @knowbee I think `ft` or `feature` would more make sens if it was about adding a new feature but this PR doesn't change the current implementation but only refactor the codebase. We can maybe have `feature` (New feature), `refactor` (Refactor the codebase), `bug` (fixing bug), `chore` (improving the development environment)

sounds about right 👌, update accordingly.

**Comment by knowbee** [comment]
> > @knowbee I think `ft` or `feature` would more make sens if it was about adding a new feature but this PR doesn't change the current implementation but only refactor the codebase. We can maybe have `feature` (New feature), `refactor` (Refactor the codebase), `bug` (fixing bug), `chore` (improving the development environment)
> 
> sounds about right 👌, update accordingly.

I have updated contributing guideline with your naming convention suggestion. [check it out](https://github.com/knowbee/rwanda/blob/master/CONTRIBUTING.md#branch-naming)

**Comment by oesukam** [comment]
@knowbee Under `Branch naming`, instead of `Summary`, I think it should be `Example` as `refactor-data-file`

**Comment by oesukam** [comment]
@knowbee If possible to also add the link to the contribution guideline in the readme for easy access

**Pull request merged**
